Q1. Consider the following sensor readings: temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40]) A sensor has an average measurement error of +2°C. Perform the following without using a for loop: a. Add 2°C to every reading using vectorization. b. Convert all temperatures from Celsius to Fahrenheit using: F =9 5 C +32 c. Identify all readings greater than 32°C using Boolean indexing. d. Count how many readings exceed 32°C. e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.


In [1]:
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

#(a)
corrected_temperature = temperature + 2

#(b)
fahrenheit = (9/5) * temperature + 32
print("Temperature in Fahrenheit:", fahrenheit)

#(c)
greater_than_32 = temperature[temperature > 32]
print("Readings greater than 32°C:", greater_than_32)

#(d)
count = np.sum(temperature > 32)
print("Number of readings greater than 32°C:", count)

#(e)
#Vectorization allows us to perform an operation on the complete NumPy array at once instead of using a for loop for every value.
#Boolean indexing allows us to select only the values satisfying a condition.
#Therefore, both methods make the program:[shorter, easier to understand, faster for large datasets, more efficient than manually checking every value]

Temperature in Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
Readings greater than 32°C: [35 38 33 40]
Number of readings greater than 32°C: 4


Q2. The following matrix represents the number of daily steps recorded by four users over three days: steps = np.array([ [5000, 6200, 7100], [8000, 7500, 9000], [4500, 5100, 4800], [9000, 8500, 9500]]) Perform the following: a. Calculate the total steps recorded. b. Calculate the mean number of steps. c. Find the maximum and minimum values. d. Calculate the total steps for each day using axis=0. e. Calculate the total steps for each user using axis=1. f. Find the user/day position containing the maximum number of steps using argmax().

In [2]:
import numpy as np
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

#(a)
total = np.sum(steps)
print("Total steps:", total)

#(b)
mean = np.mean(steps)
print("Mean steps:", mean)

#(c)
maximum = np.max(steps)
minimum = np.min(steps)
print("Maximum steps:", maximum)
print("Minimum steps:", minimum)

#(d)
day_total = np.sum(steps, axis=0)
print("Total steps for each day:", day_total)

#(e)
user_total = np.sum(steps, axis=1)
print("Total steps for each user:", user_total)

#(f)
position = np.argmax(steps)
print("Position of maximum value:", position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum value: 11


Q3. Write a Python program using NumPy to perform the following operations: a. Create the following NumPy array: original = np.array([1, 2, 3, 4, 5, 6]) b. Create a slice containing elements from index 1 to 4 and store it in a variable named subset. c. Modify the first element of subset to 999 and display both original and subset. d. Create another slice from original, but this time use .copy(). Modify its first element to 500 and display original and the copied array. e. Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it into a 3 × 4 matrix. f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing: • First row  • Last row  • Second column  • Elements from rows 1–2 and columns 2–3  g. Create a flattened version of the 3 × 4 matrix using both flatten() and ravel(). h. Modify an element in the array returned by ravel() and observe whether the original array is affected. i. Modify an element in the array returned by flatten() and observe whether the original array is affected. j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.

In [3]:
import numpy as np

#(a)
original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

#(b)
subset = original[1:5]
print("Subset:", subset)

#(c)
subset[0] = 999
print("Original:", original)
print("Subset:", subset)

#(d)
copied_array = original[1:5].copy()
copied_array[0] = 500
print("Original:", original)
print("Copied array:", copied_array)

#(e)
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

#(f)
print("First row:", matrix[0, :])
print("Last row:", matrix[-1, :])
print("Second column:", matrix[:, 1])
print("Selected elements:")
print(matrix[0:2, 1:3])

#(g)
flat1 = matrix.flatten()
print("Using flatten():", flat1)

#(h)
ravel_array = matrix.ravel()
ravel_array[0] = 100
print("Ravel array:", ravel_array)
print("Original matrix:")
print(matrix)

#(i)
matrix2 = np.arange(1, 13).reshape(3, 4)
flatten_array = matrix2.flatten()
flatten_array[0] = 500
print("Flatten array:", flatten_array)
print("Original matrix:")
print(matrix2)

#(j)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original: [1 2 3 4 5 6]
Subset: [2 3 4 5]
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Selected elements:
[[2 3]
 [6 7]]
Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel array: [100   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flatten array: [500   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


Q4. A simple cognitive-assistive system wants to predict a user's assistance score based on three factors: • Sleep hours  • Activity level  • Stress level  Consider: y = np.array([40, 65, 30, 85]) X = np.array([ [6, 70, 3], [5, 50, 6], [8, 80, 2], [4, 30, 8] ]) Here, each row represents one user and each column represents a feature. Perform the following: a. Display the shape and dimensions of X. b. Calculate: X.T and explain what the transpose represents. c. Calculate the matrix product: X.T @ X d. Calculate the matrix inverse using: np.linalg.inv() where appropriate. e. Implement the Ordinary Least Squares equation: 𝛽 = (𝑋𝑋) 𝑋𝑦 using NumPy. f. Explain what the resulting coefficients represent in the context of the three user features. g. A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to obtain a predicted assistance score.

In [4]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])

#(a)
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

#(b)
XT = X.T
print("Transpose of X:")
print(XT)

#(c)
XTX = X.T @ X
print("X.T @ X:")
print(XTX)

#(d)
inverse = np.linalg.inv(XTX)
print("Inverse:")
print(inverse)

#(e)
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("Coefficients:")
print(beta)

#(f)
#beta1 → Sleep hours
#beta2 → Activity level
#beta3 → Stress level

#(g)
new_user = np.array([5, 40, 7])
prediction = new_user @ beta
print("Predicted assistance score:", prediction)


Shape of X: (4, 3)
Dimensions of X: 2
Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
Coefficients:
[-0.15921454  0.14083853 10.06302242]
Predicted assistance score: 75.27862544779117
