Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: a) Addition of 2 in all the element  b) Multiply 3 with all the elements c) Divide every element by 2

In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 6])
print("Original Array: ", arr)
print("Addition of 2: ", arr+2)
print("Multiplied by 3: ", arr*3)
print("Dividing by 2: ", arr/2)

Original Array:  [1 2 3 4 6]
Addition of 2:  [3 4 5 6 8]
Multiplied by 3:  [ 3  6  9 12 18]
Dividing by 2:  [0.5 1.  1.5 2.  3. ]


Q.2 Questions on Basic NumPy Array: a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) b) Find the most frequent value and their indice(s) in the following arrays: i. x = np.array([1,2,3,4,5,1,2,1,1,1]) ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
arr=np.array([1, 2, 3, 6, 4, 5])

rev_arr=arr[::-1]
print("Reversed Array: ", rev_arr)

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)

most_freq = values[np.argmax(counts)]
print("Most frequent value:", most_freq)
print("Indices:", np.where(x == most_freq)[0])

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values, counts = np.unique(y, return_counts=True)

most_freq = values[np.argmax(counts)]
print("Most frequent value:", most_freq)
print("Indices:", np.where(y == most_freq)[0])

Reversed Array:  [5 4 6 3 2 1]
Most frequent value: 1
Indices: [0 5 7 8 9]
Most frequent value: 1
Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [ ]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("1st row, 2nd column", arr[0, 1])
print("3rd row, 1st column", arr[2, 0])

1st row, 2nd column 20
3rd row, 1st column 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
wnew=np.linspace(10, 100, 25)
print(new)

print("Dimentions: ", new.ndim)
print("Shape: ", new.shape)
print("Toal elements: ", new.size)
print("Data Type: ", new.dtype)
print("Total bytes: ", new.nbytes)

transpose_arr= new.reshape(25, 1)
print(transpose_arr)

row_array = new.reshape(1, 25)
print(row_array.shape)
column_array = row_array.T


[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimentions:  1
Shape:  (25,)
Toal elements:  25
Data Type:  float64
Total bytes:  200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [1]:
import numpy as np

ucs420_Namrata = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_Namrata)

print("Mean:", np.mean(ucs420_Namrata))

print("Median:", np.median(ucs420_Namrata))

print("Maximum:", np.max(ucs420_Namrata))

print("Minimum:", np.min(ucs420_Namrata))

print("Unique elements:", np.unique(ucs420_Namrata))

reshaped_ucs420_Namrata = ucs420_Namrata.reshape(4, 3)

print("Reshaped Array:")
print(reshaped_ucs420_Namrata)

resized_ucs420_Namrata = np.resize(ucs420_Namrata, (2, 3))

print("Resized Array:")
print(resized_ucs420_Namrata)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
[[10 20 30]
 [40 50 60]]
